-- +goose Up
ALTER TABLE vehicle ADD COLUMN checked_in_by INTEGER REFERENCES team_member(id) ON DELETE CASCADE NOT NULL DEFAULT 1;
ALTER TABLE vehicle ADD COLUMN checked_out_by INTEGER REFERENCES team_member(id) ON DELETE CASCADE NOT NULL DEFAULT 1;

ALTER TABLE service ADD COLUMN is_active BOOLEAN DEFAULT FALSE;