// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"
)

type Allocation struct {
	ID           int32
	TeamMemberID int32
	ParkingID    int32
	ServiceID    int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Department struct {
	ID         int32
	Name       string
	Codename   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Accesscode sql.NullString
}

type Driver struct {
	ID          int32
	Fullname    string
	PhoneNumber string
	Email       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type JwtToken struct {
	ID           int32
	AccessToken  string
	TeamMemberID int32
	IsValid      sql.NullBool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	RefreshToken sql.NullString
}

type Parkingsession struct {
	ID        int32
	StationID int32
	ServiceID int32
	Report    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Parkingstation struct {
	ID        int32
	Name      string
	Codename  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Service struct {
	ID        int32
	Name      string
	Date      time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	Time      sql.NullTime
}

type TeamMember struct {
	ID           int32
	Fullname     string
	Codename     string
	PhoneNumber  string
	Email        sql.NullString
	IsTeamLeader sql.NullBool
	IsAdmin      sql.NullBool
	DepartmentID int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Password     sql.NullString
}

type Vehicle struct {
	ID            int32
	DriverID      int32
	LicenseNumber string
	Model         sql.NullString
	SecurityNotes sql.NullString
	ParkingID     int32
	ServiceID     int32
	IsCheckedOut  sql.NullBool
	CheckInTime   sql.NullTime
	CheckOutTime  sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
