// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"
)

type Allocation struct {
	ID           uint64
	TeamMemberID sql.NullInt32
	ParkingID    sql.NullInt32
	ServiceID    sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Department struct {
	ID        uint64
	Name      sql.NullString
	Codename  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Driver struct {
	ID          uint64
	Fullname    sql.NullString
	PhoneNumber sql.NullString
	Email       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Parkingsession struct {
	ID        uint64
	StationID sql.NullInt32
	ServiceID sql.NullInt32
	Report    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Parkingstation struct {
	ID        uint64
	Name      sql.NullString
	Codename  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Service struct {
	ID        uint64
	Name      sql.NullString
	Date      time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamMember struct {
	ID           uint64
	Fullname     sql.NullString
	Codename     sql.NullString
	PhoneNumber  sql.NullString
	Email        sql.NullString
	IsTeamLeader sql.NullBool
	IsAdmin      sql.NullBool
	DepartmentID sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Vehicle struct {
	ID            uint64
	DriverID      sql.NullInt32
	LicenseNumber sql.NullString
	Model         sql.NullString
	SecurityNotes sql.NullString
	SessionID     sql.NullInt32
	IsCheckedOut  sql.NullBool
	CheckInTime   sql.NullTime
	CheckOutTime  sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
